version: '3.8'

networks:
  my-contacts:
    driver: bridge

services:
  api:
    image: api-elastic:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - my-contacts
