version: '3.8'

services:
  api:
    image: buddzbuddy/api-elastic:latest
    ports:
      - 5000:5000
    environment:
      - ES_HOST=http://localhost:9200
      - NRSZ_CONNECTION_STRING=Data Source=localhost;Initial Catalog=nrsz;Password=WestWood-911;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True;Max Pool Size=3500;Connect Timeout=300;
      - ASIST_DATA_CONNECTION_STRING=Data Source=192.168.0.66;Initial Catalog=asist-data;Password=WestWood-911;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True;Max Pool Size=3500;Connect Timeout=300;
